src/Entity/Product.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     */
    private $capacity;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Feedback", mappedBy="product")
     */
    private $feedbacks;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="products")
     */
    private $categories;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->feedbacks = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): string
    {
        return (new Slugify)->slugify($this->getTitle());
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Feedback[]
     */
    public function getFeedbacks(): Collection
    {
        return $this->feedbacks;
    }

    public function addFeedback(Feedback $feedback): self
    {
        if (!$this->feedbacks->contains($feedback)) {
            $this->feedbacks[] = $feedback;
            $feedback->setProduct($this);
        }

        return $this;
    }

    public function removeFeedback(Feedback $feedback): self
    {
        if ($this->feedbacks->contains($feedback)) {
            $this->feedbacks->removeElement($feedback);
            // set the owning side to null (unless already changed)
            if ($feedback->getProduct() === $this) {
                $feedback->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('price')
            ->add('description')
            ->add('address')
            ->add('capacity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'translation_domain'=>'forms'
        ]);
    }
}

src/Controller/ProductController.php
<?php


namespace App\Controller;


use App\Entity\Feedback;
use App\Entity\Product;
use App\Form\FeedbackType;
use App\Repository\FeedbackRepository;
use App\Repository\ProductRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    /**
     * @var ProductRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(ProductRepository $repository, ObjectManager $em)
    {

        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * * @Route("/produit/{slug}-{id}",name="product.show", requirements={"slug":"[a-z0-9\-]*"})
     * @param Product $product
     * @param $slug
     * @param FeedbackRepository $feedbackRepository
     * @param Request $request
     * @return Response
     */
    public function show(Product $product, $slug, FeedbackRepository $feedbackRepository, Request $request): Response
    {

        if ($product->getSlug() !== $slug) {
            return $this->redirectToRoute('product.show', [
                'id' => $product->getId(),
                'slug' => $product->getSlug()
            ], 301);
        }

        $feedback = new Feedback();

        $form = $this->createForm(FeedbackType::class, $feedback);

        $average = $feedbackRepository->findProductAvgNote($product);

        return $this->render('product/show.html.twig',[
            'product'=>$product,
            'notes'=>$average,
            'current_menu'=>'home',
            'form'=>$form->createView()
        ]);
    }

}

templates/product/show.html.twig
{% extends 'base.html.twig' %}


{% block title 'Nom du produit par son ID' %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h1 class="note">{{ product.title }}
                        <div>
                            <p>
                                {% for note in notes %}
                                    {% if (note.note_avg/2)|round == 1%}
                                        <i class="material-icons star">star</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i>
                                    {% elseif (note.note_avg/2)|round == 2 %}
                                        <i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i>
                                    {% elseif (note.note_avg/2)|round == 3 %}
                                        <i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star_border</i><i class="material-icons star">star_border</i>
                                    {% elseif (note.note_avg/2)|round == 4 %}
                                        <i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star_border</i>
                                    {% elseif (note.note_avg/2)|round == 5 %}
                                        <i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i><i class="material-icons star">star</i>
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </div>
                    </h1>
                </div>
                <div class="col-4">
                    <button class="btn btn-success btn-lg float-right">Réserver</button>
                </div>
            </div>
            <div class="row">
                {#IMAGE SLIDER#}
                <div class="col-8">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-warp="false">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="http://placehold.it/650x400" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="http://placehold.it/650x400" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="http://placehold.it/650x400" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                {#FIN IMAGE SLIDER#}
                <div class="col-4">
                    <h3>Description</h3>
                    <p>{{ product.description }}</p>

                    <h3>CARTE DE LA POSITION DU PRODUIT</h3>
                    <div id="map">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mb-4">
        <h2>Informations complémentaires</h2>
        <div class="row">
            <div class="col-4">
                <p>Date d'arrivée:</p>
                <p>Date de départ:</p>
            </div>
            <div class="col-4">
                <p>Capacité: {{ product.capacity }}</p>
                <p>Catégorie:
                    {% for category in product.categories %}
                        {{ category.name }}
                        {{ not loop.last ? ',' }}
                    {% endfor %}</p>
            </div>
            <div class="col-4">
                <p>Adresse: {{ product.address }}</p>
                <p>Tarif: {{ product.price }}€</p>
            </div>
        </div>
    </div>
    <div class="container mb-4">
        {% for message in app.flashes('success')  %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Commentaire</th>
                <th scope="col">Note</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% if product.feedbacks is empty %}
                <tr>
                    Il n'y a pas encore de commentaire sur ce produit ! N'hésitez pas à en poster un !
                </tr>
            {% endif %}
                {%  for feedback in product.feedbacks  %}
                <tr>
                    <th scope="row">{{ feedback.id }}</th>
                    <td>{{ feedback.comment }}</td>
                    <td>{{ feedback.note }}</td>
                    <td>{{ feedback.createdAt | date('d-m-Y') }}</td>
                </tr>
                {%  endfor  %}
            </tbody>
        </table>

        <button class="btn btn-primary right" data-toggle="modal" data-target="#feedback_modal">Ajouter un commentaire</button>



        <div class="modal fade" id="feedback_modal" tabindex="-1" role="dialog" aria-labelledby="feedback_modal_label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="feedback_modal_label">Nouveau commentaire</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                            {{ form_start(form, {'attr': {'id': 'feedback_form'}}) }}
                                {{ form_row(form.note) }}
                                {{ form_row(form.comment) }}
                            <button class="btn btn-primary">Valider</button>
                            {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div id="div_id" data-id="{{ product.id }}" style="display: none"></div>
{% endblock %}

{% block javascripts  %}
    <script>
        let route = Routing.generate('product.feedback.new', {id: $('#div_id').data('id')});

        $('#feedback_form').on('submit',function(e){
            e.preventDefault();
                $.ajax({
                    url: location.origin + route,
                    data: {
                        comment : $("#feedback_comment").val(),
                        note :$("#feedback_note").val()
                    },
                    xhrFields: {
                        withCredentials: true
                    },
                    method: 'POST'
                }).done(function(data){
                    $('#feedback_modal').modal('hide');
                    location.reload();
                }).fail(function(error){
                    console.log('Nop');
                    alert(error);
                });


        });
    </script>
{% endblock %}